/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.knappm124.inventorytracker.userinterface;

import com.knappm124.inventorytracker.collections.Collections;
import com.knappm124.inventorytracker.collections.Item;
import com.knappm124.inventorytracker.collections.Location;
import com.knappm124.inventorytracker.collections.Status;

/**
 *
 * @author melyg
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    Collections c;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        c = new Collections();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutPane = new javax.swing.JOptionPane();
        PopUpNewItem = new javax.swing.JFrame();
        NewItemLabel = new java.awt.Label();
        panel1 = new java.awt.Panel();
        PopUpNewItemNameLabel = new javax.swing.JLabel();
        PopUpNewItemPriceLabel = new javax.swing.JLabel();
        PopUpNewItemLocationLabel = new javax.swing.JLabel();
        PopUpNewItemStatusLabel = new javax.swing.JLabel();
        PopUpNewItemTagsLabel = new javax.swing.JLabel();
        PopUpNewItemName = new javax.swing.JTextField();
        PopUpNewItemPrice = new javax.swing.JTextField();
        PopUpNewItemLocation = new javax.swing.JComboBox<>();
        PopUpNewItemStatus = new javax.swing.JComboBox<>();
        PopUpNewItemTagColorLabel = new javax.swing.JLabel();
        PopUpNewItemTagColor = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        PopUpNewItemSaveButton = new javax.swing.JButton();
        PopUpNewItemCancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuNewCollection = new javax.swing.JMenuItem();
        MenuNewItem = new javax.swing.JMenuItem();
        MenuFilter = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuExit = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        MenuEditTag = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuEditLocations = new javax.swing.JMenuItem();
        MenuEditItem = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuAbout = new javax.swing.JMenuItem();

        AboutPane.setMessage("Inventory Tracker was created by Melissa Knapp");

        NewItemLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NewItemLabel.setText("New Item");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PopUpNewItemNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PopUpNewItemNameLabel.setText("Name");

        PopUpNewItemPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PopUpNewItemPriceLabel.setText("Price");

        PopUpNewItemLocationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PopUpNewItemLocationLabel.setText("Location");

        PopUpNewItemStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PopUpNewItemStatusLabel.setText("Status");

        PopUpNewItemTagsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PopUpNewItemTagsLabel.setText("Tags");

        PopUpNewItemName.setText("Item Name");
        PopUpNewItemName.addActionListener(this::PopUpNewItemNameActionPerformed);

        PopUpNewItemPrice.setText("Price");

        PopUpNewItemLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etsy", "General Store", "Home" }));
        PopUpNewItemLocation.addActionListener(this::PopUpNewItemLocationActionPerformed);

        PopUpNewItemStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WIP", "Listed", "Sold", "Returned" }));

        PopUpNewItemTagColorLabel.setText("Color");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Red", "Orange", "Yellow", "Green", "Blue", "Purple" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PopUpNewItemTagColor.setViewportView(jList1);

        PopUpNewItemSaveButton.setText("Save");
        PopUpNewItemSaveButton.addActionListener(this::PopUpNewItemSaveButtonActionPerformed);

        PopUpNewItemCancelButton.setText("Cancel");
        PopUpNewItemCancelButton.addActionListener(this::PopUpNewItemCancelButtonActionPerformed);

        javax.swing.GroupLayout PopUpNewItemLayout = new javax.swing.GroupLayout(PopUpNewItem.getContentPane());
        PopUpNewItem.getContentPane().setLayout(PopUpNewItemLayout);
        PopUpNewItemLayout.setHorizontalGroup(
            PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpNewItemLayout.createSequentialGroup()
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PopUpNewItemLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PopUpNewItemLayout.createSequentialGroup()
                                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PopUpNewItemLocationLabel)
                                    .addComponent(PopUpNewItemNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PopUpNewItemPriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PopUpNewItemStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PopUpNewItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PopUpNewItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PopUpNewItemLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PopUpNewItemStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PopUpNewItemLayout.createSequentialGroup()
                                .addComponent(PopUpNewItemTagsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PopUpNewItemTagColor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PopUpNewItemTagColorLabel))
                                .addGap(156, 156, 156)))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addGroup(PopUpNewItemLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PopUpNewItemSaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(PopUpNewItemCancelButton)))
                .addContainerGap())
        );
        PopUpNewItemLayout.setVerticalGroup(
            PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PopUpNewItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopUpNewItemNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopUpNewItemPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopUpNewItemLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopUpNewItemStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemTagColorLabel)
                    .addComponent(PopUpNewItemTagsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PopUpNewItemTagColor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PopUpNewItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopUpNewItemCancelButton)
                    .addComponent(PopUpNewItemSaveButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuFile.setText("File");

        MenuNewCollection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuNewCollection.setText("New Collection");
        MenuFile.add(MenuNewCollection);

        MenuNewItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuNewItem.setText("New Item");
        MenuFile.add(MenuNewItem);

        MenuFilter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuFilter.setText("Filter");
        MenuFilter.addActionListener(this::MenuFilterActionPerformed);
        MenuFile.add(MenuFilter);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        MenuFile.add(jMenuItem2);
        MenuFile.add(jSeparator1);

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuExit.setText("Close");
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        MenuEdit.setText("Edit");

        MenuEditTag.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuEditTag.setText("Tags");
        MenuEdit.add(MenuEditTag);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Statuses");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        MenuEdit.add(jMenuItem1);

        MenuEditLocations.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuEditLocations.setText("Locations");
        MenuEdit.add(MenuEditLocations);

        MenuEditItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuEditItem.setText("Items");
        MenuEdit.add(MenuEditItem);

        jMenuBar1.add(MenuEdit);

        MenuHelp.setText("Help");

        MenuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuAbout.setText("About");
        MenuAbout.addActionListener(this::MenuAboutActionPerformed);
        MenuHelp.add(MenuAbout);

        jMenuBar1.add(MenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        AboutPane.setVisible(true);
    }//GEN-LAST:event_MenuAboutActionPerformed

    private void MenuFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFilterActionPerformed

    private void PopUpNewItemLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpNewItemLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopUpNewItemLocationActionPerformed

    private void PopUpNewItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpNewItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopUpNewItemNameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void PopUpNewItemSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpNewItemSaveButtonActionPerformed
       String name = PopUpNewItemName.getText();
       String price = PopUpNewItemPrice.getText();
       Object status = PopUpNewItemStatus.getSelectedItem();
       Object location = PopUpNewItemLocation.getSelectedItem();
       String temp = (String) status;
       temp = temp.toUpperCase();
       String id = (String) location;
       Location l = c.getLocation(id);
       try{
           Double priceDouble = Double.valueOf(price);
           Item i = new Item.ItemBuilder(name).withPrice(priceDouble).withStatus(Status.valueOf(temp)).withLocationId(l.getId()).build();
           c.addItem(i);
       } catch (Exception e){
           //TODO: Exception handling logic
       }
    }//GEN-LAST:event_PopUpNewItemSaveButtonActionPerformed

    private void PopUpNewItemCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpNewItemCancelButtonActionPerformed
       
    }//GEN-LAST:event_PopUpNewItemCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane AboutPane;
    private javax.swing.JMenuItem MenuAbout;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenuItem MenuEditItem;
    private javax.swing.JMenuItem MenuEditLocations;
    private javax.swing.JMenuItem MenuEditTag;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuFilter;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuNewCollection;
    private javax.swing.JMenuItem MenuNewItem;
    private java.awt.Label NewItemLabel;
    private javax.swing.JFrame PopUpNewItem;
    private javax.swing.JButton PopUpNewItemCancelButton;
    private javax.swing.JComboBox<String> PopUpNewItemLocation;
    private javax.swing.JLabel PopUpNewItemLocationLabel;
    private javax.swing.JTextField PopUpNewItemName;
    private javax.swing.JLabel PopUpNewItemNameLabel;
    private javax.swing.JTextField PopUpNewItemPrice;
    private javax.swing.JLabel PopUpNewItemPriceLabel;
    private javax.swing.JButton PopUpNewItemSaveButton;
    private javax.swing.JComboBox<String> PopUpNewItemStatus;
    private javax.swing.JLabel PopUpNewItemStatusLabel;
    private javax.swing.JScrollPane PopUpNewItemTagColor;
    private javax.swing.JLabel PopUpNewItemTagColorLabel;
    private javax.swing.JLabel PopUpNewItemTagsLabel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
